#!/usr/bin/env bash
set -e

PYTHON=venv/bin/python

$PYTHON -m venmo.drop_table rent
$PYTHON -m venmo.drop_table users

for file in venmo/migrations/*.py; do
  basename=$(basename $file)
  migration=${basename%.py}
  echo "Running $migration ..."
  $PYTHON -m venmo.migrations.$migration
done
